config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'bemvindo' => 'home#index'

  root 'home#index'

  resources :phones
  resources :addresses
  resources :contacts
  resources :kinds
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :kind
  has_one :address
  # has_many :phones

  accepts_nested_attributes_for :address
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[show edit update destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show; end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @contact.build_address

    options_for_select
  end

  # GET /contacts/1/edit
  def edit
    options_for_select
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def options_for_select
    @kind_options_for_select = Kind.all
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Contact.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def contact_params
    params.require(:contact).permit(:nome, :email, :kind_id, :rmk, address_attributes: [:street, :city, :state])
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true, html: { class: "basic-grey" }) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h1>Contacts</h1>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :kind_id %>
    <%= collection_select(:contact, :kind_id, @kind_options_for_select, :id, :description) %>
  </div>

  <%= form.fields_for :address do |address_fields| %>
    <div class="field">
      <%= form.label :street %>
      <%= address_fields.text_field :street %>
    </div>
    <div class="field">
      <%= form.label :city %>
      <%= address_fields.text_field :city %>
    </div>
    <div class="field">
      <%= form.label :state %>
      <%= address_fields.text_field :state %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rmk %>
    <%= form.text_area :rmk %>
  </div>

  <div class="actions">
    <%= form.submit "Enviar", class: "button" %>
    <%= link_to 'Back', contacts_path, class: "button" %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th><%= Contact.human_attribute_name("name") %></th>
      <th><%= Contact.human_attribute_name("email") %></th>
      <th><%= Contact.human_attribute_name("kind") %></th>
      <th><%= Contact.human_attribute_name("rmk") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.nome %></td>
        <td><%= contact.email %></td>
        <td><%= contact.kind %></td>
        <td><%= contact.rmk %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<%= render 'form', contact: @contact %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @contact.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @contact.kind %>
</p>

<p>
  <strong>Rmk:</strong>
  <%= @contact.rmk %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>